# Generated by Django 6.0.3 on 2026-03-10 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_number", models.CharField(max_length=20, unique=True)),
                ("admission_date", models.DateField(auto_now_add=True)),
                ("roll_number", models.CharField(max_length=10)),
                ("current_class", models.CharField(max_length=50)),
                ("section", models.CharField(max_length=10)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                ("emergency_contact", models.CharField(max_length=15)),
                ("emergency_contact_name", models.CharField(max_length=100)),
                ("father_name", models.CharField(max_length=100)),
                ("father_phone", models.CharField(max_length=15)),
                ("father_occupation", models.CharField(blank=True, max_length=100)),
                ("mother_name", models.CharField(max_length=100)),
                ("mother_phone", models.CharField(max_length=15)),
                ("mother_occupation", models.CharField(blank=True, max_length=100)),
                ("present_address", models.TextField()),
                ("permanent_address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["current_class", "section", "roll_number"],
            },
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("birth_certificate", "Birth Certificate"),
                            ("id_proof", "ID Proof"),
                            ("address_proof", "Address Proof"),
                            ("previous_marksheet", "Previous Marksheet"),
                            ("transfer_certificate", "Transfer Certificate"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("document_file", models.FileField(upload_to="student_documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("student", "date")},
            },
        ),
    ]
